-- Active: 1722075190982@@127.0.0.1@3306@db1
use  db1;
CREATE table blogPost(P_id INT PRIMARY KEY AUTO_INCREMENT,p_acc VARCHAR(40),p_des VARCHAR(60),p_url VARCHAR(1000)NOT NULL);
SELECT * FROM blogPost;
TRUNCATE Table blogPost;
ALTER Table blogPost MODIFY COLUMN  p_acc VARCHAR(40) UNIQUE;
CREATE Table user (a_name VARCHAR(20) PRIMARY KEY,u_name VARCHAR(20) NOT NULL,u_email VARCHAR(40) UNIQUE NOT NULL,u_num BIGINT(10),u_pass VARCHAR(10) NOT NULL,u_gen VARCHAR(40),u_dob DATE NOT NULL,pro_pic VARCHAR(40) NOT NULL,pro_bio VARCHAR(200) NOT NULL DEFAULT "Add Something about Yourself");
ALTER TABLE `user` ADD COLUMN followin INT NOT NULL DEFAULT 0;
SELECT * FROM user;
DESC blogpost;
DESC user;
TRUNCATE Table follow;
ALTER TABLE blogpost DROP COLUMN comment ;
DROP Table pcomment;
ALTER TABLE `blogpost` ADD `Stime` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ;
DELETE FROM blogpost WHERE p_des='mskmckdsjn';
ALTER Table blogpost ADD COLUMN comment int DEFAULT 0;
CREATE TABLE pcomment(c_id INT PRIMARY KEY AUTO_INCREMENT,P_id INT,u_name VARCHAR(40) NOT NULL,c_dis VARCHAR(40) NOT NULL,c_time TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , Foreign Key (P_id) REFERENCES blogpost(P_id) on delete CASCADE on update cascade );
SELECT * FROM pcomment;
DROP Table user;
DELETE FROM pcomment WHERE c_id=6;
SELECT comment from blogpost WHERE comment>0;
UPDATE `user`set followin=0;
CREATE TABLE follow( x VARCHAR(20) NOT NULL, y VARCHAR(20) NOT NULL, frole ENUM('follower','following'), FOREIGN KEY(x) REFERENCES user(a_name) on delete CASCADE on update CASCADE);
SELECT * from follow;
select x from follow where y='shiva' and frole='follower';
select x from follow where x like '%shiv%' and y='kai' and frole='following';
select * from pcomment where P_id='$r[P_id]' order by c_time;
update user set  pro_bio= 'Write Something' ;
ALTER Table `user` MODIFY COLUMN pro_pic VARCHAR(100) NOT NULL;
UPDATE `user` set followin=1 WHERE a_name='shiva' ;
select u_email , u_pass from user where a_name='kai';
DELETE FROM `user` WHERE a_name='sitaram_14';
DELETE FROM blogpost WHERE p_acc='sitaram_14';
UPDATE `user` set followin=followin-1 WHERE a_name in (SELECT DISTINCT (x) FROM follow WHERE y='kai' AND frole='following');
UPDATE `user` set follower=follower-1 WHERE a_name in (SELECT DISTINCT (x) FROM follow WHERE y='kai' AND frole='follower');
SELECT COUNT(DISTINCT (x))  FROM follow WHERE y='sitaram_14' AND frole='following';
UPDATE `user` set followin=followin-1 WHERE a_name in (SELECT DISTINCT (x) FROM follow WHERE y='sitaram_14' AND frole='following');
UPDATE `user` set follower=follower-1 WHERE a_name in (SELECT DISTINCT (x) FROM follow WHERE y='sitaram_14' AND frole='follower');
DELETE FROM pcomment WHERE u_name='shiva';
SELECT (P_id),COUNT(u_name) FROM pcomment WHERE P_id in (SELECT (P_id) from pcomment WHERE u_name='kai');
SELECT P_id, COUNT(u_name) FROM pcomment WHERE u_name='kai' GROUP BY P_id;
UPDATE blogpost SET comment=comment-1 WHERE P_id=18;
TRUNCATE Table follow ;
SELECT DISTINCT (y) FROM follow WHERE x='kai' AND frole='follower';
DELETE from follow where y='shreya_21' and frole='following';
ALTER Table blogpost DROP COLUMN comment;
SELECT P_id, COUNT(P_id) FROM pcomment WHERE u_name='shreya_21' GROUP BY P_id;
select count(P_id) from pcomment where P_id=18;
